export const WORLD_CAPITALS = [
  { country: "Afganistán", city: "Kabul" },
  { country: "Albania", city: "Tirana" },
  { country: "Alemania", city: "Berlin" },
  { country: "Andorra", city: "Andorra la Vella" },
  { country: "Angola", city: "Luanda" },
  { country: "Antigua y Barbuda", city: "Saint John's" },
  { country: "Arabia Saudita", city: "Riyadh" },
  { country: "Argelia", city: "Algiers" },
  { country: "Argentina", city: "Buenos Aires" },
  { country: "Armenia", city: "Yerevan" },
  { country: "Australia", city: "Canberra" },
  { country: "Austria", city: "Vienna" },
  { country: "Azerbaiyán", city: "Baku" },
  { country: "Bahamas", city: "Nassau" },
  { country: "Bangladés", city: "Dhaka" },
  { country: "Barbados", city: "Bridgetown" },
  { country: "Baréin", city: "Manama" },
  { country: "Bélgica", city: "Brussels" },
  { country: "Belice", city: "Belmopan" },
  { country: "Benín", city: "Porto-Novo" },
  { country: "Bielorrusia", city: "Minsk" },
  { country: "Birmania", city: "Naypyidaw" },
  { country: "Bolivia", city: "La Paz" },
  { country: "Bosnia y Herzegovina", city: "Sarajevo" },
  { country: "Botsuana", city: "Gaborone" },
  { country: "Brasil", city: "Brasilia" },
  { country: "Brunéi", city: "Bandar Seri Begawan" },
  { country: "Bulgaria", city: "Sofia" },
  { country: "Burkina Faso", city: "Ouagadougou" },
  { country: "Burundi", city: "Gitega" },
  { country: "Bután", city: "Thimphu" },
  { country: "Cabo Verde", city: "Praia" },
  { country: "Camboya", city: "Phnom Penh" },
  { country: "Camerún", city: "Yaounde" },
  { country: "Canadá", city: "Ottawa" },
  { country: "Catar", city: "Doha" },
  { country: "Chad", city: "N'Djamena" },
  { country: "Chile", city: "Santiago" },
  { country: "China", city: "Beijing" },
  { country: "Chipre", city: "Nicosia" },
  { country: "Ciudad del Vaticano", city: "Vatican City" },
  { country: "Colombia", city: "Bogota" },
  { country: "Comoras", city: "Moroni" },
  { country: "Corea del Norte", city: "Pyongyang" },
  { country: "Corea del Sur", city: "Seoul" },
  { country: "Costa de Marfil", city: "Yamoussoukro" },
  { country: "Costa Rica", city: "San Jose" },
  { country: "Croacia", city: "Zagreb" },
  { country: "Cuba", city: "Havana" },
  { country: "Dinamarca", city: "Copenhagen" },
  { country: "Dominica", city: "Roseau" },
  { country: "Ecuador", city: "Quito" },
  { country: "Egipto", city: "Cairo" },
  { country: "El Salvador", city: "San Salvador" },
  { country: "Emiratos Árabes Unidos", city: "Abu Dhabi" },
  { country: "Eritrea", city: "Asmara" },
  { country: "Eslovaquia", city: "Bratislava" },
  { country: "Eslovenia", city: "Ljubljana" },
  { country: "España", city: "Madrid" },
  { country: "Estados Unidos", city: "Washington D.C." },
  { country: "Estonia", city: "Tallinn" },
  { country: "Etiopía", city: "Addis Ababa" },
  { country: "Filipinas", city: "Manila" },
  { country: "Finlandia", city: "Helsinki" },
  { country: "Fiyi", city: "Suva" },
  { country: "Francia", city: "Paris" },
  { country: "Gabón", city: "Libreville" },
  { country: "Gambia", city: "Banjul" },
  { country: "Georgia", city: "Tbilisi" },
  { country: "Ghana", city: "Accra" },
  { country: "Granada", city: "St. George's" },
  { country: "Grecia", city: "Athens" },
  { country: "Guatemala", city: "Guatemala City" },
  { country: "Guinea ecuatorial", city: "Malabo" },
  { country: "Guinea", city: "Conakry" },
  { country: "Guinea-Bisáu", city: "Bissau" },
  { country: "Guyana", city: "Georgetown" },
  { country: "Haití", city: "Port-au-Prince" },
  { country: "Honduras", city: "Tegucigalpa" },
  { country: "Hungría", city: "Budapest" },
  { country: "India", city: "New Delhi" },
  { country: "Indonesia", city: "Jakarta" },
  { country: "Irak", city: "Baghdad" },
  { country: "Irán", city: "Tehran" },
  { country: "Irlanda", city: "Dublin" },
  { country: "Islandia", city: "Reykjavik" },
  { country: "Islas Marshall", city: "Majuro" },
  { country: "Islas Salomón", city: "Honiara" },
  { country: "Israel", city: "Jerusalem" },
  { country: "Italia", city: "Rome" },
  { country: "Jamaica", city: "Kingston" },
  { country: "Japón", city: "Tokyo" },
  { country: "Jordania", city: "Amman" },
  { country: "Kazajistán", city: "Astana" },
  { country: "Kenia", city: "Nairobi" },
  { country: "Kirguistán", city: "Bishkek" },
  { country: "Kiribati", city: "Tarawa" },
  { country: "Kuwait", city: "Kuwait City" },
  { country: "Laos", city: "Vientiane" },
  { country: "Lesoto", city: "Maseru" },
  { country: "Letonia", city: "Riga" },
  { country: "Líbano", city: "Beirut" },
  { country: "Liberia", city: "Monrovia" },
  { country: "Libia", city: "Tripoli" },
  { country: "Liechtenstein", city: "Vaduz" },
  { country: "Lituania", city: "Vilnius" },
  { country: "Luxemburgo", city: "Luxembourg" },
  { country: "Macedonia del Norte", city: "Skopje" },
  { country: "Madagascar", city: "Antananarivo" },
  { country: "Malasia", city: "Kuala Lumpur" },
  { country: "Malaui", city: "Lilongwe" },
  { country: "Maldivas", city: "Male" },
  { country: "Malí", city: "Bamako" },
  { country: "Malta", city: "Valletta" },
  { country: "Marruecos", city: "Rabat" },
  { country: "Mauricio", city: "Port Louis" },
  { country: "Mauritania", city: "Nouakchott" },
  { country: "México", city: "Mexico City" },
  { country: "Micronesia", city: "Palikir" },
  { country: "Moldavia", city: "Chisinau" },
  { country: "Mónaco", city: "Monaco" },
  { country: "Mongolia", city: "Ulaanbaatar" },
  { country: "Montenegro", city: "Podgorica" },
  { country: "Mozambique", city: "Maputo" },
  { country: "Namibia", city: "Windhoek" },
  { country: "Nauru", city: "Yaren" },
  { country: "Nepal", city: "Kathmandu" },
  { country: "Nicaragua", city: "Managua" },
  { country: "Níger", city: "Niamey" },
  { country: "Nigeria", city: "Abuja" },
  { country: "Noruega", city: "Oslo" },
  { country: "Nueva Zelanda", city: "Wellington" },
  { country: "Omán", city: "Muscat" },
  { country: "Países Bajos", city: "Amsterdam" },
  { country: "Pakistán", city: "Islamabad" },
  { country: "Palaos", city: "Ngerulmud" },
  { country: "Panamá", city: "Panama City" },
  { country: "Papúa Nueva Guinea", city: "Port Moresby" },
  { country: "Paraguay", city: "Asuncion" },
  { country: "Perú", city: "Lima" },
  { country: "Polonia", city: "Warsaw" },
  { country: "Portugal", city: "Lisbon" },
  { country: "Reino Unido", city: "London" },
  { country: "República Centroafricana", city: "Bangui" },
  { country: "República Checa", city: "Prague" },
  { country: "República del Congo", city: "Brazzaville" },
  { country: "República Democrática del Congo", city: "Kinshasa" },
  { country: "República Dominicana", city: "Santo Domingo" },
  { country: "Ruanda", city: "Kigali" },
  { country: "Rumania", city: "Bucharest" },
  { country: "Rusia", city: "Moscow" },
  { country: "Samoa", city: "Apia" },
  { country: "San Cristóbal y Nieves", city: "Basseterre" },
  { country: "San Marino", city: "San Marino" },
  { country: "San Vicente y las Granadinas", city: "Kingstown" },
  { country: "Santa Lucía", city: "Castries" },
  { country: "Santo Tomé y Príncipe", city: "São Tomé" },
  { country: "Senegal", city: "Dakar" },
  { country: "Serbia", city: "Belgrade" },
  { country: "Seychelles", city: "Victoria" },
  { country: "Sierra Leona", city: "Freetown" },
  { country: "Singapur", city: "Singapore" },
  { country: "Siria", city: "Damascus" },
  { country: "Somalia", city: "Mogadishu" },
  { country: "Sri Lanka", city: "Sri Jayawardenepura Kotte" },
  { country: "Suazilandia", city: "Mbabane" },
  { country: "Sudáfrica", city: "Pretoria" },
  { country: "Sudán del Sur", city: "Juba" },
  { country: "Sudán", city: "Khartoum" },
  { country: "Suecia", city: "Stockholm" },
  { country: "Suiza", city: "Bern" },
  { country: "Surinam", city: "Paramaribo" },
  { country: "Tailandia", city: "Bangkok" },
  { country: "Tanzania", city: "Dodoma" },
  { country: "Tayikistán", city: "Dushanbe" },
  { country: "Timor Oriental", city: "Dili" },
  { country: "Togo", city: "Lomé" },
  { country: "Tonga", city: "Nukuʻalofa" },
  { country: "Trinidad y Tobago", city: "Port of Spain" },
  { country: "Túnez", city: "Tunis" },
  { country: "Turkmenistán", city: "Ashgabat" },
  { country: "Turquía", city: "Ankara" },
  { country: "Tuvalu", city: "Funafuti" },
  { country: "Ucrania", city: "Kyiv" },
  { country: "Uganda", city: "Kampala" },
  { country: "Uruguay", city: "Montevideo" },
  { country: "Uzbekistán", city: "Tashkent" },
  { country: "Vanuatu", city: "Port Vila" },
  { country: "Venezuela", city: "Caracas" },
  { country: "Vietnam", city: "Hanoi" },
  { country: "Yemen", city: "Sanaa" },
  { country: "Yibuti", city: "Djibouti" },
  { country: "Zambia", city: "Lusaka" },
  { country: "Zimbabue", city: "Harare" }
];
